pipeline {
    agent none

    stages {

        stage('Checkout') {
            agent any
            steps {
                echo 'Checkout completed'
                // checkout scm
            }
        }

        stage('Build and Test') {
            agent {
                docker {
                    image 'maven:3.9.6-eclipse-temurin-17'
                    args '--user root -v /var/run/docker.sock:/var/run/docker.sock'
                }
            }
            steps {
                sh '''
                    cd spring-boot-app
                    mvn clean package
                '''
            }
        }

        stage('Static Code Analysis') {
            agent {
                docker {
                    image 'maven:3.9.6-eclipse-temurin-17'
                    args '--user root -v /var/run/docker.sock:/var/run/docker.sock'
                }
            }
            environment {
                SONAR_URL = "http://100.27.198.157:9000"
            }
            steps {
                withCredentials([string(credentialsId: 'sonarqube', variable: 'SONAR_AUTH_TOKEN')]) {
                    sh '''
                        cd spring-boot-app
                        mvn sonar:sonar \
                        -Dsonar.token=$SONAR_AUTH_TOKEN \
                        -Dsonar.host.url=$SONAR_URL
                    '''
                }
            }
        }

        stage('Build and Push Docker Image') {
            agent any

            environment {
                DOCKER_IMAGE = "surendra157/ultimate-cicd:${BUILD_NUMBER}"
            }

            steps {
                script {

                    sh '''
                        cd spring-boot-app
                        docker build -t ${DOCKER_IMAGE} .
                    '''

                    docker.withRegistry('https://index.docker.io/v1/', 'docker-cred') {
                        docker.image("${DOCKER_IMAGE}").push()
                    }
                }
            }
        }

        stage('Update Deployment File') {
            agent any

            environment {
                GIT_REPO_NAME = "End-to-End-CICD-using-jenkins"
                GIT_USER_NAME = "surendrapradeep157"
            }

            steps {
                withCredentials([string(credentialsId: 'github', variable: 'GITHUB_TOKEN')]) {

                    sh '''
                        git config --global user.email "surendrapradeep157@gmail.com"
                        git config --global user.name "Surendra Pradeep S"

                        sed -i "s/replaceImageTag/${BUILD_NUMBER}/g" spring-boot-app-manifests/deployment.yml

                        git add spring-boot-app-manifests/deployment.yml

                        git commit -m "Update deployment image to version ${BUILD_NUMBER}" || true

                        git push https://${GITHUB_TOKEN}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME}.git HEAD:main
                    '''
                }
            }
        }
    }
}